### ISSUE TITLE
Unwanted characters in window status

### ISSUE THREAD

**Issue by omar2205** [charlietag/tmux-split-statusbar#1]
![image](https://user-images.githubusercontent.com/1373867/125157249-14ff7100-e16a-11eb-8607-00413c26356b.png)

28 and 26 are `status-left-length` and `status-right-length`

**Comment by charlietag** [comment]
Dear @omar2205 ,
Can you show me the result of this command in this tmux status?
Thanks !
`tmux show-option -g`

**Comment by omar2205** [comment]
Hey @charlietag, thanks for getting back to me, 
![image](https://user-images.githubusercontent.com/1373867/125578197-8e3ac203-4e3d-4e75-98a5-1658d5e0dcae.png)
I suspect those are the culprit, do you know how to remove them?

**Comment by charlietag** [comment]
Hi @omar2205 ,
## Solution
I hope this could help you to remove them.

Modify this file manually:
`~/.tmux/plugins/tmux-split-statusbar/scripts/helpers.sh`
```diff
-46: status_format_0_tobe="$(echo "${status_format_0_default}" | sed 's/:status-left//g' | sed 's/:status-right//g')"
+46: status_format_0_tobe="$(echo "${status_format_0_default}" | sed 's/:status-left//g' | sed 's/:status-right//g' | sed 's#T;=/##g' )"
```

## Tmux source code
* But these are tmux default parameters, I'm not sure what they are really for.
  Ref. https://github.com/tmux/tmux/blob/master/options-table.c#L85

    ```
    /* Status line format. */
    #define OPTIONS_TABLE_STATUS_FORMAT1 \
    	"#[align=left range=left #{status-left-style}]" \
    	"#[push-default]" \
    	"#{T;=/#{status-left-length}:status-left}" \
    	"#[pop-default]" \
    	"#[norange default]" \
    ```

**Comment by omar2205** [comment]
That almost did it
![image](https://user-images.githubusercontent.com/1373867/125586960-2068271b-75cc-4a86-ac20-8cea8b71f6a9.png)
it still say the length (just the numbers now)

**Comment by charlietag** [comment]
Hi @omar2205 ,
I've push a new commit for this.

https://github.com/charlietag/tmux-split-statusbar/commit/ddd6e6ab295f93e2c7ae8d6e6feb5db21a2b36cb#diff-e015cc3ac522b202bb23852488a7ac2c019e2c82568ecb387b97b60ebbecdf4b

Can you try to undo the change and update the repo to the latest status.

# Command
## Undo changes
`git checkout ~/.tmux/plugins/tmux-split-statusbar/scripts/helpers.sh`

## Update the repo to the latest status
`cd ~/.tmux/plugins/tmux-split-statusbar`

`git pull`

**Comment by omar2205** [comment]
Yep, it worked, thanks.
